services:
  database:
    image: 'mariadb:10.5'
    container_name: 'database'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'
    healthcheck: # healthcheck check mariadb and set service 'healthy' accordingly
      test: mysqladmin ping -h 127.0.0.1 -u root --password=admin
    tty: true
    # l'alignement doit être le même que pour les autres parties
    volumes:
      - ./mariadb/:/var/lib/mysql/