server:
  port: 8180

spring:
  application:
    name: offer
  datasource:
    url: jdbc:mysql://localhost/agregio
    username: agregio
    password: agregio
    driver-class-name: org.mariadb.jdbc.Driver
